name: Feature Request
description: Suggest an idea
labels: ["enhancement"]
title: "Feature: "
body:
  - type: markdown
    attributes:
      value: Before getting started, please checked the [GitHub Issues](https://github.com/lin-stephanie/obsidian-url-display/issues) (open or closed) and there are no similar issues.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Goal or desired outcome
      description: Before describing your requested feature, please describe more generally the problem, pain-point, or use case you'd like to solve for.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Feature description
      description: Please describe the desired feature in as much detail as you are able.
  - type: textarea
    attributes:
      label: Any alternatives or work-arounds
      description: Some features may take time to develop, it may be helpful for you and others to have alternative options or workarounds, and may help clarify the feature itself.
  - type: textarea
    attributes:
      label: Additional context
      description: If applicable, add any other context or screenshots to help explain the request.